//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Group
    {
        public Group()
        {
            this.Missions = new HashSet<Mission>();
            this.Rebels = new HashSet<Rebel>();
        }
    
        public int group_id { get; set; }
        public string group_name { get; set; }
        public string territory { get; set; }
    
        public virtual ICollection<Mission> Missions { get; set; }
        public virtual ICollection<Rebel> Rebels { get; set; }
    }
}
